// symcheck as a title: print which imported functions are null.
//
// In an installed title, an import that no system module exports is left
// pointing at nothing, and the first call through it is a jump to address 0
// (how arena step 9 died in Memory::Initialize). A payload gets a different
// kernel library, so ps5/probes/symcheck/main.c passing as a payload says
// nothing about a title. This takes the address of every name on the list and
// reports the ones that are null. Print-only: it calls none of them.
//
// title_names.inc is generated by build.sh from another ELF's import list:
//   X(index, name)

#include <cstdio>
#include <cstring>
#include <unistd.h>

#include "title_log.h"

#define X(index, name) extern char mcla_import_##index[] __asm__(#name);
#include "title_names.inc"
#undef X

namespace {

struct Import {
  const char* name;
  const void* address;
};

const Import kImports[] = {
#define X(index, name) {#name, mcla_import_##index},
#include "title_names.inc"
#undef X
};

void Line(const char* text) {
  (void)!write(g_mcla_log_fd, text, std::strlen(text));
  (void)!write(g_mcla_log_fd, "\n", 1);
}

__attribute__((constructor(101))) void Connect() {
  MclaTitleLogConnect();
}

}  // namespace

int main() {
  char text[256];
  const int count = static_cast<int>(sizeof kImports / sizeof kImports[0]);
  std::snprintf(text, sizeof text, "symcheck title: %d names", count);
  Line(text);
  int missing = 0;
  for (int i = 0; i < count; ++i) {
    // volatile: the compiler may otherwise assume the address of a declared
    // object is never null and drop the test.
    const void* volatile address = kImports[i].address;
    if (address == nullptr) {
      std::snprintf(text, sizeof text, "NULL %s", kImports[i].name);
      Line(text);
      ++missing;
    }
  }
  std::snprintf(text, sizeof text, "symcheck title: %d null of %d", missing, count);
  Line(text);
  return 0;
}
