// Development aid for function recovery.
//
// Functions reached only through pointers (static initialisers, vtables,
// callbacks) are invisible to the recompiler's call-graph analysis and fail at
// run time one at a time. This scans the loaded image's data for values that
// look like pointers to function entries the recompiler did not emit, and
// writes them as TOML hints for review. It reads guest memory only; nothing
// from the image is written out except the addresses.

#include "generated/default/mcla_init.h"

#include "mcla_app.h"

#include <cstdint>
#include <cstdio>
#include <set>
#include <string>

#include <rex/cvar.h>
#include <rex/logging.h>
#include <rex/runtime.h>
#include <rex/system/function_dispatcher.h>
#include <rex/system/xmemory.h>

REXCVAR_DEFINE_STRING(mcla_scan_code_pointers, "", "MCLA",
                      "Write unrecovered function-pointer candidates to this TOML file, then exit");

namespace {

// default.xex 0.0.0.8 layout, from the XEX page descriptors (docs/phase0-recon.md).
constexpr uint32_t kImageBase = 0x82000000;
constexpr uint32_t kCodeBegin = 0x82130000;
constexpr uint32_t kCodeEnd = 0x827CD054;
constexpr uint32_t kImageEnd = 0x829E0000;

constexpr uint32_t kBlr = 0x4E800020;
constexpr uint32_t kBctr = 0x4E800420;

uint32_t ReadBE(const rex::memory::Memory* memory, uint32_t address) {
  const uint8_t* p = memory->TranslateVirtual<const uint8_t*>(address);
  return (uint32_t(p[0]) << 24) | (uint32_t(p[1]) << 16) | (uint32_t(p[2]) << 8) | p[3];
}

// A function entry normally follows the end of another function: a return, an
// indirect jump, an unconditional branch (tail call), or alignment padding.
bool FollowsFunctionEnd(const rex::memory::Memory* memory, uint32_t address) {
  if (address == kCodeBegin) {
    return true;
  }
  uint32_t prev = ReadBE(memory, address - 4);
  if (prev == kBlr || prev == kBctr || prev == 0) {
    return true;
  }
  // b target (opcode 18, AA=0, LK=0)
  return (prev & 0xFC000003) == 0x48000000;
}

}  // namespace

void MclaApp::OnPreLaunchModule() {
  std::string out_path = REXCVAR_GET(mcla_scan_code_pointers);
  if (out_path.empty()) {
    InstallCrashTrace();
    return;
  }
  auto* memory = runtime()->memory();
  auto* dispatcher = runtime()->function_dispatcher();

  std::set<uint32_t> candidates;
  uint32_t pointers_seen = 0;
  for (uint32_t address = kImageBase; address + 4 <= kImageEnd; address += 4) {
    if (address >= kCodeBegin && address < kCodeEnd) {
      continue;
    }
    uint32_t value = ReadBE(memory, address);
    if (value < kCodeBegin || value >= kCodeEnd || (value & 3)) {
      continue;
    }
    ++pointers_seen;
    if (dispatcher->GetFunction(value)) {
      continue;
    }
    if (ReadBE(memory, value) == 0 || !FollowsFunctionEnd(memory, value)) {
      continue;
    }
    candidates.insert(value);
  }

  if (FILE* f = std::fopen(out_path.c_str(), "w")) {
    std::fprintf(f, "# Generated by --mcla_scan_code_pointers. Review before use.\n");
    for (uint32_t address : candidates) {
      std::fprintf(f, "[functions.\"0x%08X\"]\nname = \"sub_%08X\"\n\n", address, address);
    }
    std::fclose(f);
  }
  REXLOG_INFO("code pointer scan: {} code pointers in data, {} unrecovered candidates -> {}",
              pointers_seen, candidates.size(), out_path);
  std::exit(0);
}
